package com.increff.omni.reporting.commons;

import com.nextscm.commons.spring.common.ApiException;
import com.nextscm.commons.spring.common.ApiStatus;
import com.nextscm.commons.spring.common.ErrorData;
import com.nextscm.commons.spring.common.FieldErrorData;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.HttpStatus;
import org.springframework.validation.BindException;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;

@ControllerAdvice
public abstract class AbstractRestappControllerAdvice {

    @ResponseStatus(value = HttpStatus.INTERNAL_SERVER_ERROR)
    @ExceptionHandler(Throwable.class)
    @ResponseBody
    public ErrorData handleUnknownException(HttpServletRequest req, Throwable t) {
        ErrorData data = new ErrorData();
        data.setCode(ApiStatus.UNKNOWN_ERROR);
        data.setMessage("Internal error");
        data.setDescription(fromThrowable(t));
        return data;
    }

    // Convert a predefined exception to an HTTP Status code
    @ResponseStatus(value = HttpStatus.BAD_REQUEST)
    @ExceptionHandler(ApiException.class)
    @ResponseBody
    public ErrorData handleApiException(HttpServletRequest req, ApiException e, HttpServletResponse response) {
        // No need to log ApiExceptions. They are generated by the code
        ErrorData data = new ErrorData();
        data.setCode(e.getStatus());
        data.setMessage(e.getMessage());
        data.setDescription(fromThrowable(e.getCause()));
        data.setErrors(e.getErrors());
        return data;
    }

    // Convert a predefined exception to an HTTP Status code
    @ResponseStatus(value = HttpStatus.BAD_REQUEST)
    @ExceptionHandler(BindException.class)
    @ResponseBody
    public ErrorData handleBindException(HttpServletRequest req, BindException e) {
        // No need to log anything
        return handleBindingResult(e.getBindingResult());
    }

    // Convert a predefined exception to an HTTP Status code
    @ResponseStatus(value = HttpStatus.BAD_REQUEST)
    @ExceptionHandler(MethodArgumentNotValidException.class)
    @ResponseBody
    public ErrorData handleArgumentException(HttpServletRequest req, MethodArgumentNotValidException e) {
        // No need to log anything
        return handleBindingResult(e.getBindingResult());
    }

    public static ErrorData handleBindingResult(BindingResult br) {
        List<FieldErrorData> errors = new ArrayList<>();
        for (FieldError ferror : br.getFieldErrors()) {
            FieldErrorData fdata = new FieldErrorData();
            fdata.setCode(ferror.getCode());
            fdata.setField(ferror.getField());
            fdata.setMessage(ferror.getDefaultMessage());
            errors.add(fdata);
        }
        ErrorData data = new ErrorData();
        data.setCode(ApiStatus.BAD_DATA);
        data.setMessage("Bad input provided");
        data.setErrors(errors);
        return data;
    }

    // TODO this is only for initial POC, so that we can debug easily.
    // Remove this for a full product
    public static String fromThrowable(Throwable t) {
        if (t == null) {
            return null;
        }
        // Return stack trace as a string
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        t.printStackTrace(pw);
        return sw.toString();
    }

}
