package com.increff.omni.reporting.model.constants;

public enum AuditActions {
    ADD_ORGANIZATION,
    EDIT_ORGANIZATION,
    ADD_CONNECTION,
    EDIT_CONNECTION,
    ADD_ORGANIZATION_MAPPING,
    EDIT_ORGANIZATION_MAPPING,
    ADD_DASHBOARD,
    EDIT_DASHBOARD,
    CREATE_REPORT,
    EDIT_REPORT,
    UPSERT_REPORT_QUERY,
    REQUEST_REPORT,
    LIVE_REPORT,
    CREATE_REPORT_SCHEDULE,
    EDIT_REPORT_SCHEDULE,
    ENABLE_DISABLE_REPORT_SCHEDULE,
    DELETE_REPORT_SCHEDULE,
    DELETE_FAVOURITE,
    DELETE_DASHBOARD
}
