package com.increff.omni.reporting.model.constants;

public enum AuditActions {
    EDIT_CONNECTION,
    ORGANIZATION_SCHEMA_VERSION_MAPPING,
    ORGANIZATION_CONNECTION_MAPPING,
    CREATE_REPORT,
    EDIT_REPORT,
    UPSERT_REPORT_QUERY,
    REQUEST_REPORT,
    CREATE_REPORT_SCHEDULE,
    EDIT_REPORT_SCHEDULE,
    ENABLE_DISABLE_REPORT_SCHEDULE,
    DELETE_REPORT_SCHEDULE
}
